// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"
)

type User struct {
<<<<<<< HEAD
	ID        int32
=======
	ID        string
>>>>>>> e5a6370aa5f3252380ec1f3e5f0dd89eb89f3ce4
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}
