version: "3.8"

services:
  db:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test-blogator
    ports:
      - "5432:5432"
    # volumes:  # Remove this volume mapping to use ephemeral storage
    #   - db-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      - CONN=postgres://user:password@db:5432/test-blogator?sslmode=disable
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app

volumes:
  app-data:
